name: 'dark-mechanicum/aws-codebuild'
author: 'Andrei  Kazakou <a.v.kazakou@gmail.com>'
description: 'GitHub Action to execute AWS CodeBuild jobs'
branding:
  icon: 'upload-cloud'
  color: 'orange'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  projectName:
    description: 'The name of the CodeBuild build project to start running a build'
    required: true
