name: 'dark-mechanicum/aws-codebuild'
main: 'dist/index.js'
description: 'GitHub Action to execute AWs CodeBuild jobs'
inputs:
  projectName:
    description: 'The name of the CodeBuild build project to start running a build'
    required: true
runs:
  using: 'node16'
  main: 'index.js'