name: Validation
on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  simple:
    name: AWS CodeBuild
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Executing AWS CodeBuild task
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        with:
          projectName: 'testing-codebuild-logs'
          redirectServiceURL: 'https://cloudaws.link/r/'
          buildspec: '{
            "environmentVariablesOverride":[
              { "name":"testEnvVar", "value":"Testing environment variable", "type": "PLAINTEXT" }
            ],
            "logsConfigOverride": {
              "cloudWatchLogs": {
                "status": "ENABLED"
              }
            }
          }'
