name: Create new v1 release
on:
  release:
    types: [published]

jobs:
  updating_tag:
    name: Release v1 version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Git User
        uses: fregante/setup-git-user@v1

      - name: Remove remove v1 tag
        run: git push origin :refs/tags/v1

      - name: Update v1 tag locally
        run: git tag -fa v1 -m "Pointing v1 to the ${{ github.ref }}"

      - name: Push tags to the remote
        run: git push origin main --tags

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1
          release_name: Major release version
          body: Update major release version to the ${{ github.ref }}
          draft: false
          prerelease: false

  deploy:
    needs: [ updating_tag ]
    name: Validate v1 release updates
    runs-on: ubuntu-latest
    steps:
      - name: Executing AWS CodeBuild task
        uses: dark-mechanicum/aws-codebuild@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        with:
          projectName: 'testing-codebuild-logs'
          redirectServiceURL: 'https://cloudaws.link/r/'
          buildspec: '{
            "environmentVariablesOverride":[
              { "name":"testEnvVar", "value":"Testing environment variable", "type": "PLAINTEXT" }
            ],
            "logsConfigOverride": {
              "cloudWatchLogs": {
                "status": "ENABLED"
              }
            }
          }'